config:
  data_path:
    ticker_list:
      directory: "basepath/01_raw/ohlcv"
      file_name: "tickers_yfinance"
      file_format: "csv"
      versioned: TRUE

    ticker_data:
      directory: "basepath/01_raw/ohlcv"
      file_name: "data_yfinance"
      file_format: "csv"
      versioned: TRUE

    pct_change_matrix:
      directory: "basepath/02_processed/pct_change"
      file_name: "pct_change_matrix"
      file_format: "csv"
      versioned: TRUE

    correlation_matrix:
      directory: "basepath/02_processed/correlation_matrix"
      file_name: "correlation_edges"
      file_format: "csv"
      versioned: TRUE

    valuation_input_matrix:      
      directory: "basepath/02_processed/valuation_input_matrix"
      file_name: "valuation_input_matrix"
      file_format: "csv"
      versioned: TRUE

    valuation_scores_full_matrix:      
      directory: "basepath/02_processed/valuation_scores_matrix"
      file_name: "valuation_scores_matrix"
      file_format: "csv"
      versioned: TRUE

    valuation_scores_latest_matrix:      
      directory: "basepath/03_analysis/valuation/valuation_scores_latest_matrix"
      file_name: "valuation_scores_matrix"
      file_format: "csv"
      versioned: TRUE

    adjusted_pairs_matrix:
      directory: "basepath/02_processed/adjusted_pairs"
      file_name: "adjusted_pairs"
      file_format: "csv"
      versioned: TRUE

    filtered_pairs_matrix:
      directory: "basepath/03_analysis/correlation/filtered_pairs"
      file_name: "filtered_pairs"
      file_format: "csv"
      versioned: TRUE

  data:

    # Tickers must be yfin compliant
    tickers:
      - HDFCSML250.NS
      - HDFCGOLD.NS
      - HDFCNEXT50.NS
    
    # Must be less than 3 years
    window_in_days: 900
    vix: ^INDIAVIX

  parameters:
    correlation:

      # Method of correlation to use
      method: pearson # OPTIONAL: kendall | spearman
      
      # Metric to see the correlation in
      metrics:
        - open
        - high
        - low
        - close
        - adj_close

      # Number of top pairs to return
      filter:
        filter_n_pairs: TRUE
        top_n_pairs: 10
        filter_inverse_threshold: FALSE
        inverse_threshold: -0.10


      # Minimum obsv for corr
      min_observations: 60

      # Optimize to find equities for low, negative
      optimization_strategy: negative

    valuation:

      # Method to perform valuation
      # Options are ['price_z_score', 'log_price_z_score', 'log_return_z_score', 'all']
      method: log_return_z_score 

      # Rolling Window to calculate the valuation for
      window_in_days: 400

      # Metric used to compute the valuation are
      metric: adj_close

      # Clip values
      clip: 0

      # Bounded Flag
      apply_bounding: TRUE

    portfolio_params:
      number_of_securities: 10