config:
  data_path:
    ticker_list:
      directory: "basepath/01_raw/ohlcv"
      file_name: "tickers_yfinance"
      file_format: "csv"
      versioned: TRUE

    ticker_data:
      directory: "basepath/01_raw/ohlcv"
      file_name: "data_yfinance"
      file_format: "csv"
      versioned: TRUE

    pct_change_matrix:
      directory: "basepath/02_processed/pct_change"
      file_name: "pct_change_matrix"
      file_format: "csv"
      versioned: TRUE

    correlation_matrix:
      directory: "basepath/02_processed/correlation_matrix"
      file_name: "correlation_edges"
      file_format: "csv"
      versioned: TRUE

    valuation_input_matrix:
      directory: "basepath/02_processed/valuation_input_matrix"
      file_name: "valuation_input_matrix"
      file_format: "csv"
      versioned: TRUE

    valuation_scores_full_matrix:
      directory: "basepath/02_processed/valuation_scores_matrix"
      file_name: "valuation_scores_matrix"
      file_format: "csv"
      versioned: TRUE

    valuation_scores_latest_matrix:
      directory: "basepath/03_analysis/valuation/valuation_scores_latest_matrix"
      file_name: "valuation_scores_matrix"
      file_format: "csv"
      versioned: TRUE

    adjusted_pairs_matrix:
      directory: "basepath/02_processed/adjusted_pairs"
      file_name: "adjusted_pairs"
      file_format: "csv"
      versioned: TRUE

    filtered_pairs_matrix:
      directory: "basepath/03_analysis/correlation/filtered_pairs"
      file_name: "filtered_pairs"
      file_format: "csv"
      versioned: TRUE

  data:
    # Tickers must be yfin compliant
    tickers:
      - HDFCSML250.NS
      - HDFCGOLD.NS
      - HDFCNEXT50.NS
      - AMBUJACEM.NS
      - ASIANPAINT.NS
      - EIDPARRY.NS
      - ETERNAL.NS
      - GMRAIRPORT.NS
      - HDFCBANK.NS
      - ABC.NS
      - ITC.NS
      - LLOYDSME.NS
      - NBCC.NS
      - OLECTRA.NS
      - PCBL.NS

    # Must be less than 3 years
    window_in_days: 900
    vix: ^INDIAVIX

  parameters:
    correlation:
      # Method of correlation to use
      method: spearman # OPTIONAL: kendall | spearman

      # Metric to see the correlation in
      metrics:
        - open
        - high
        - low
        - close
        - adj_close

      # Minimum obsv for corr
      min_observations: 60

    portfolio_params:
      # Anchor points
      correlation_anchor_points: 5

      # Max bucket Size, Can be positive int or NULL
      max_bucket_size: 8
